version: '3.8'
# for local development
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker-compose/nginx/Dockerfile
    ports:
      - 8765:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
  php:
    build: 
      context: .
      dockerfile: ./docker-compose/php/Dockerfile
    volumes:
      - ./:/var/www/html